### ISSUE TITLE
Dark Mode - Change Escalation Key Color to stand out more

### ISSUE THREAD

**Issue by darkufo** [avm99963/infinitegforums#11]
Currently in dark mode the escalation and locked keys are not always obvious.

![chrome_S281lnqOSI](https://user-images.githubusercontent.com/12990410/92572599-8df91800-f27c-11ea-98c7-be6c07bdde0a.png)

![chrome_6ECxVL7oIO](https://user-images.githubusercontent.com/12990410/92572936-fba54400-f27c-11ea-8c73-1d94e71c5d10.png)

Maybe something similar to this to make it "pop out" more when quickly scrolling.

![chrome_ieYHvshtTg](https://user-images.githubusercontent.com/12990410/92572773-c698f180-f27c-11ea-8c21-30e33016cfd4.png)

**Comment by avm99963** [comment]
I like that, thanks for the suggestion!

I also just realized that those lock/key icons are in the same div as the title text, and so for read threads the `opacity: 0.8` rule we added yesterday also affects the icons :( I'll also be fixing this.
