### ISSUE TITLE
FR: Redirect all threads to CC toggle

### ISSUE THREAD

**Issue by DennisLfromGA** [avm99963/infinitegforums#5]
I know the option to "Redirect all threads opened in TW to the Community Console. (experimental)" is experimental, it even says so. ;-)

![Screenshot 2019-08-22 at 10 53 50 AM](https://user-images.githubusercontent.com/3418772/63525334-862cd100-c4cb-11e9-8233-0418fa878459.png)

I love this feature *but* it would be nice if we could toggle it off when desired to open the thread in the forum.

-**DennisLfromGA**

**P.S.** Love the extension, thanx much!

**Comment by avm99963** [comment]
Hey Dennis!

Thanks to the new TW change (the Community Console link is now visible on all threads, even if you're not an expert in them) now this can be done in a straightforward way, so I'm going to implement it right now.

**Comment by avm99963** [comment]
I just made another change which helps switch the "Redirect all threads [...]" function on and off: now clicking the extension icon in the extensions toolbar will open the options page!
